# Exemple ISO 
# Auteur: ISO/CHATGPT
# Relecture : non
# Objectif : oui 

def get_data():
    return [
        {"model":"Themes","data":{"id_theme":21,"theme":"ISO"}},
        {"model":"Domaines","data":{"id_theme":21,"id_domaine":211,"domaine":"Audit Organisationnel"}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21101 ,"chapitre":"Politiques de sécurité de l'information"}},
        {"model":"Questions","data":{"id_chapitre": 21101,"question":"Avez-vous une politique formelle de sécurité de l'information en place ?","objectif":"La vérification de l'existence de cette politique est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21101,"question":"La politique de sécurité de l'information est-elle régulièrement revue et mise à jour ?","objectif":"La révision régulière de cette politique est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21102 ,"chapitre":"Rôles et responsabilités en matière de sécurité de l'information"}},
        {"model":"Questions","data":{"id_chapitre": 21102,"question":"Les rôles et responsabilités liés à la sécurité de l'information sont-ils clairement définis ?","objectif":"La définition claire des rôles est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21102,"question":"Les employés sont-ils formés pour comprendre leurs responsabilités en matière de sécurité de l'information ?","objectif":"La formation des employés est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21103 ,"chapitre":"Séparation des fonctions"}},
        {"model":"Questions","data":{"id_chapitre": 21103,"question":"Y a-t-il une séparation des fonctions critiques pour limiter les risques d'abus ?","objectif":"La séparation des fonctions est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21103,"question":"Les accès aux systèmes sensibles sont-ils limités à des groupes distincts d’utilisateurs ?","objectif":"Le contrôle des accès séparés est jugé ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21104 ,"chapitre":"Responsabilités de la direction"}},
        {"model":"Questions","data":{"id_chapitre": 21104,"question":"La direction joue-t-elle un rôle actif dans la mise en œuvre des politiques de sécurité ?","objectif":"L’implication de la direction est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21104,"question":"La direction effectue-t-elle des évaluations périodiques des risques liés à la sécurité de l'information ?","objectif":"L'évaluation des risques par la direction est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21105 ,"chapitre":"Contact avec les autorités"}},
        {"model":"Questions","data":{"id_chapitre": 21105,"question":"Avez-vous établi des contacts formels avec les autorités locales pour la gestion des incidents de sécurité ?","objectif":"La coopération avec les autorités est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21105,"question":"Des procédures sont-elles en place pour signaler les incidents de sécurité aux autorités compétentes ?","objectif":"La mise en place de ces procédures est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21106 ,"chapitre":"Contact avec les groupes d'intérêts spéciaux"}},
        {"model":"Questions","data":{"id_chapitre": 21106,"question":"L’organisation participe-t-elle à des groupes d’intérêts spéciaux liés à la sécurité de l'information ?","objectif":"La participation à ces groupes est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21106,"question":"Avez-vous des relations avec des associations professionnelles pour suivre les évolutions en matière de sécurité de l'information ?","objectif":"La collaboration avec des associations professionnelles est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21107 ,"chapitre":"Renseignements sur les menaces"}},
        {"model":"Questions","data":{"id_chapitre": 21107,"question":"L'organisation reçoit-elle régulièrement des informations sur les menaces émergentes ?","objectif":"La réception d’informations sur les menaces est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21107,"question":"Disposez-vous de mécanismes pour partager ces renseignements au sein de l'entreprise ?","objectif":"Le partage interne de ces informations est jugé ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21108 ,"chapitre":"Sécurité de l'information dans la gestion de projet"}},
        {"model":"Questions","data":{"id_chapitre": 21108,"question":"Les risques liés à la sécurité de l'information sont-ils pris en compte lors de la gestion de projet ?","objectif":"L'intégration des aspects sécurité dans la gestion de projet est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21108,"question":"Les projets intègrent-ils des exigences spécifiques en matière de sécurité de l'information ?","objectif":"L'intégration de ces exigences est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21109 ,"chapitre":"Inventaire des informations et autres actifs associés"}},
        {"model":"Questions","data":{"id_chapitre": 21109,"question":"Disposez-vous d'un inventaire détaillé des informations et actifs associés ?","objectif":"L'inventaire des actifs est jugé ..."}},
        {"model":"Questions","data":{"id_chapitre": 21109,"question":"L’inventaire des actifs est-il régulièrement mis à jour ?","objectif":"La mise à jour de l'inventaire est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21110 ,"chapitre":"Utilisation acceptable de l'information et des autres biens associés"}},
        {"model":"Questions","data":{"id_chapitre": 21110,"question":"Avez-vous une politique sur l’utilisation acceptable des informations et des biens associés ?","objectif":"L'existence de cette politique est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21110,"question":"Les utilisateurs sont-ils informés de cette politique et formés à son respect ?","objectif":"La formation des utilisateurs à cette politique est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21111 ,"chapitre":"Rendement des actifs"}},
        {"model":"Questions","data":{"id_chapitre": 21111,"question":"Le rendement des actifs technologiques est-il surveillé et optimisé régulièrement ?","objectif":"La surveillance du rendement est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21112 ,"chapitre":"Classification des informations"}},
        {"model":"Questions","data":{"id_chapitre": 21112,"question":"Les informations sont-elles classifiées selon leur niveau de sensibilité ?","objectif":"La classification des informations est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21112,"question":"La classification est-elle revue et mise à jour régulièrement ?","objectif":"La révision régulière de la classification est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21113 ,"chapitre":"Étiquetage des informations"}},
        {"model":"Questions","data":{"id_chapitre": 21113,"question":"Les informations sensibles sont-elles étiquetées conformément à leur niveau de classification ?","objectif":"L’étiquetage des informations est jugé ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21114 ,"chapitre":"Transfert d'informations"}},
        {"model":"Questions","data":{"id_chapitre": 21114,"question":"Disposez-vous de procédures sécurisées pour le transfert d'informations sensibles ?","objectif":"La sécurisation du transfert des informations est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21114,"question":"Les transferts d'informations sont-ils journalisés pour assurer leur traçabilité ?","objectif":"La journalisation des transferts est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21115 ,"chapitre":"Contrôle d'accès"}},
        {"model":"Questions","data":{"id_chapitre": 21115,"question":"Le contrôle d’accès aux systèmes et informations est-il basé sur des politiques définies ?","objectif":"L’application de politiques strictes est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21115,"question":"Des audits d'accès sont-ils effectués régulièrement pour vérifier la conformité ?","objectif":"L’audit régulier des accès est jugé ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21116 ,"chapitre":"Gestion des identités"}},
        {"model":"Questions","data":{"id_chapitre": 21116,"question":"Disposez-vous d’un système centralisé pour la gestion des identités ?","objectif":"La gestion centralisée des identités est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21117 ,"chapitre":"Informations d'authentification"}},
        {"model":"Questions","data":{"id_chapitre": 21117,"question":"Les informations d'authentification sont-elles protégées par des mesures de sécurité robustes ?","objectif":"La protection des informations d'authentification est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21118 ,"chapitre":"Droits d'accès"}},
        {"model":"Questions","data":{"id_chapitre": 21118,"question":"Les droits d'accès sont-ils basés sur le principe du moindre privilège ?","objectif":"L'application du principe du moindre privilège est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21119 ,"chapitre":"Sécurité de l'information dans les relations avec les fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21119,"question":"Les fournisseurs sont-ils soumis à des exigences de sécurité de l'information avant de travailler avec l’organisation ?","objectif":"La mise en place de ces exigences est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21120 ,"chapitre":"Prise en compte de la sécurité des informations dans les accords avec les fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21120,"question":"Les accords avec les fournisseurs incluent-ils des clauses sur la sécurité de l'information ?","objectif":"L'intégration de clauses de sécurité dans les accords est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21121 ,"chapitre":"Surveillance des services des fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21121,"question":"Les fournisseurs sont-ils soumis à une surveillance continue pour assurer le respect des exigences de sécurité de l'information ?","objectif":"La surveillance continue est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21121,"question":"Des indicateurs de performance liés à la sécurité de l'information sont-ils définis pour évaluer la qualité des services fournis ?","objectif":"La définition d'indicateurs de performance est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21121,"question":"3. **Des audits ou évaluations périodiques sont-ils menés pour vérifier la conformité des fournisseurs aux exigences de sécurité ?","objectif":"La conduite d'audits périodiques est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21122 ,"chapitre":"Suivi,révision et gestion des changements des services des fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21122,"question":"Les services fournis par les partenaires sont-ils régulièrement révisés pour garantir le respect des normes de sécurité ?","objectif":"La révision des services est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21122,"question":"Les changements dans les services des fournisseurs sont-ils documentés et analysés pour évaluer leur impact sur la sécurité ?","objectif":"La gestion des changements est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21123 ,"chapitre":"Surveillance et audit des fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21123,"question":"Effectuez-vous des audits réguliers de vos fournisseurs en matière de sécurité de l'information ?","objectif":"L’audit des fournisseurs est jugé ..."}},
        {"model":"Questions","data":{"id_chapitre": 21123,"question":"Les contrats de vos fournisseurs incluent-ils des dispositions sur la réalisation d'audits de sécurité ?","objectif":"L'inclusion de clauses d'audit dans les contrats est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21124 ,"chapitre":"Gestion des risques liés aux fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21124,"question":"Disposez-vous d’une évaluation des risques liés aux fournisseurs de services critiques ?","objectif":"L’évaluation des risques fournisseurs est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21124,"question":"Les risques identifiés liés aux fournisseurs sont-ils gérés selon une approche de réduction des risques ?","objectif":"La gestion proactive des risques liés aux fournisseurs est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21125 ,"chapitre":"Communication des exigences de sécurité aux fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21125,"question":"Les exigences de sécurité de l'information sont-elles clairement communiquées aux fournisseurs avant le début de la prestation ?","objectif":"La communication des exigences est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21126 ,"chapitre":"Gestion des incidents chez les fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21126,"question":"Les fournisseurs ont-ils des procédures définies pour gérer les incidents de sécurité de l'information ?","objectif":"L'existence de procédures chez les fournisseurs est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21126,"question":"Les incidents de sécurité chez les fournisseurs sont-ils communiqués à votre organisation en temps opportun ?","objectif":"La communication rapide des incidents est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21127 ,"chapitre":"Résiliation des contrats des fournisseurs et retour des actifs"}},
        {"model":"Questions","data":{"id_chapitre": 21127,"question":"Des procédures existent-elles pour la résiliation des contrats de fournisseurs,y compris la récupération des actifs sensibles ?","objectif":"La gestion de la fin de la relation contractuelle est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21128 ,"chapitre":"Accès des fournisseurs aux systèmes internes"}},
        {"model":"Questions","data":{"id_chapitre": 21128,"question":"Les fournisseurs ont-ils un accès limité aux systèmes internes et sont-ils soumis à un contrôle strict ?","objectif":"La limitation et le contrôle des accès des fournisseurs sont jugés ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21129 ,"chapitre":"Formation et sensibilisation des fournisseurs"}},
        {"model":"Questions","data":{"id_chapitre": 21129,"question":"Les fournisseurs sont-ils formés aux pratiques de sécurité de l'information requises par l'organisation ?","objectif":"La formation des fournisseurs est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21130 ,"chapitre":"Préparation des TIC à la continuité des activités"}},
        {"model":"Questions","data":{"id_chapitre": 21130,"question":"Disposez-vous d’un plan de continuité des activités pour les systèmes TIC en cas d'incident majeur ?","objectif":"La mise en place d'un plan de continuité est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21130,"question":"Les plans de continuité des TIC sont-ils régulièrement testés pour garantir leur efficacité ?","objectif":"La vérification de l'efficacité des plans est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21131 ,"chapitre":"Préparation des TIC à la continuité des activités"}},
        {"model":"Questions","data":{"id_chapitre": 21131,"question":"Disposez-vous d’un plan de continuité des activités pour les technologies de l'information et de la communication (TIC) ?","objectif":"La préparation des TIC à la continuité est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":211,"id_chapitre": 21132 ,"chapitre":"Droits de propriété intellectuelle"}},
        {"model":"Questions","data":{"id_chapitre": 21132,"question":"Les droits de propriété intellectuelle sont-ils respectés dans l’utilisation des logiciels et contenus ?","objectif":"Le respect des droits de propriété intellectuelle est jugé ..."}},
        
        {"model":"Domaines","data":{"id_theme":21,"id_domaine":212,"domaine":"Audit des ressources humaines"}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21201,"chapitre":"Filtrage"}},
        {"model":"Questions","data":{"id_chapitre": 21201,"question":"Effectuez-vous des contrôles de filtrage des employés avant leur embauche ?","objectif":"La vérification du filtrage des employés est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21201,"question":"Le filtrage des employés est-il revu périodiquement pour s'assurer de sa conformité ?","objectif":"La révision périodique du filtrage est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21202,"chapitre":"Conditions d'emploi"}},
        {"model":"Questions","data":{"id_chapitre": 21202,"question":"Les contrats d'emploi incluent-ils des clauses relatives à la sécurité de l'information ?","objectif":"La vérification des clauses dans les contrats est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21202,"question":"Les conditions d'emploi sont-elles régulièrement mises à jour pour inclure de nouvelles exigences de sécurité ?","objectif":"La mise à jour des conditions d'emploi est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21203,"chapitre":"Sensibilisation,éducation et formation à la sécurité de l'information"}},
        {"model":"Questions","data":{"id_chapitre": 21203,"question":"Organisez-vous des formations régulières sur la sécurité de l'information pour vos employés ?","objectif":"La vérification de l'existence de formations est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21203,"question":"Les formations sont-elles adaptées aux différents rôles au sein de l'organisation ?","objectif":"La personnalisation des formations par rôle est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21204,"chapitre":"Procédure disciplinaire"}},
        {"model":"Questions","data":{"id_chapitre": 21204,"question":"Disposez-vous d'une procédure disciplinaire pour les violations des politiques de sécurité de l'information ?","objectif":"La présence d'une procédure disciplinaire est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21204,"question":"Les sanctions disciplinaires sont-elles clairement communiquées aux employés ?","objectif":"La communication des sanctions est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21205,"chapitre":"Responsabilités après la cessation ou le changement d'emploi"}},
        {"model":"Questions","data":{"id_chapitre": 21205,"question":"Disposez-vous d'une procédure pour récupérer les actifs et révoquer les accès après la cessation d'emploi ?","objectif":"La gestion des actifs et des accès après un départ est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21205,"question":"Les responsabilités liées à la sécurité sont-elles formellement réassignées en cas de changement d'emploi interne ?","objectif":"La réassignation des responsabilités est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21206,"chapitre":"Accords de confidentialité ou de non-divulgation"}},
        {"model":"Questions","data":{"id_chapitre": 21206,"question":"Les employés signent-ils des accords de confidentialité ou de non-divulgation à leur embauche ?","objectif":"La signature de ces accords est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21206,"question":"Ces accords sont-ils également en place pour les employés temporaires ou contractuels ?","objectif":"La vérification de l'extension des accords aux employés temporaires est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21207,"chapitre":"Travail à distance"}},
        {"model":"Questions","data":{"id_chapitre": 21207,"question":"Disposez-vous de politiques spécifiques pour sécuriser le travail à distance ?","objectif":"La mise en place de politiques spécifiques pour le travail à distance est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21207,"question":"Les employés travaillant à distance utilisent-ils des connexions sécurisées (comme des VPN) ?","objectif":"L'utilisation de connexions sécurisées est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":212,"id_chapitre": 21208,"chapitre":"Rapport sur les événements de sécurité de l'information"}},
        {"model":"Questions","data":{"id_chapitre": 21208,"question":"Les employés sont-ils formés pour signaler tout événement de sécurité de l'information ?","objectif":"La formation au signalement est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21208,"question":"Disposez-vous d'un processus formel pour enquêter sur les événements de sécurité de l'information signalés ?","objectif":"La mise en place d'un processus d'enquête est jugée ..."}},

        {"model":"Domaines","data":{"id_theme":21,"id_domaine":213,"domaine":"Audit physique"}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21301,"chapitre":"Périmètres de sécurité physique"}},
        {"model":"Questions","data":{"id_chapitre": 21301,"question":"Disposez-vous de périmètres de sécurité physique clairement définis pour protéger les installations sensibles ?","objectif":"La vérification des périmètres physiques est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21301,"question":"Les périmètres de sécurité physique sont-ils régulièrement revus et mis à jour en fonction des risques ?","objectif":"L'actualisation des périmètres est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21302,"chapitre":"Entrée physique"}},
        {"model":"Questions","data":{"id_chapitre": 21302,"question":"Disposez-vous de contrôles d'accès physique pour limiter l'entrée aux personnes autorisées ?","objectif":"La vérification des contrôles d'accès physique est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21302,"question":"Les entrées physiques sont-elles surveillées et enregistrées pour des vérifications ultérieures ?","objectif":"La surveillance des entrées physiques est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21303,"chapitre":"Sécurisation des bureaux,salles et installations"}},
        {"model":"Questions","data":{"id_chapitre": 21303,"question":"Les bureaux,salles et installations sensibles sont-ils sécurisés avec des dispositifs de verrouillage adaptés ?","objectif":"La sécurisation des bureaux et installations est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21303,"question":"Disposez-vous de mesures supplémentaires pour sécuriser les zones critiques en dehors des heures de travail ?","objectif":"Les mesures supplémentaires en dehors des heures de travail sont jugées ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21304,"chapitre":"Surveillance de la sécurité physique"}},
        {"model":"Questions","data":{"id_chapitre": 21304,"question":"Disposez-vous de systèmes de surveillance vidéo pour les zones sensibles ?","objectif":"La surveillance vidéo est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21304,"question":"Les enregistrements de surveillance sont-ils conservés pour une durée appropriée et protégés contre les manipulations ?","objectif":"La conservation sécurisée des enregistrements est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21305,"chapitre":"Protection contre les menaces physiques et environnementales"}},
        {"model":"Questions","data":{"id_chapitre": 21305,"question":"Disposez-vous de mesures de protection contre les menaces physiques telles que le vol ou le vandalisme ?","objectif":"La protection contre les menaces physiques est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21305,"question":"Les installations sont-elles protégées contre les risques environnementaux tels que les incendies et inondations ?","objectif":"La protection contre les risques environnementaux est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21306,"chapitre":"Travailler dans des zones sécurisées"}},
        {"model":"Questions","data":{"id_chapitre": 21306,"question":"Les employés sont-ils informés des exigences de sécurité lorsqu'ils travaillent dans des zones sécurisées ?","objectif":"La sensibilisation des employés aux exigences des zones sécurisées est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21306,"question":"L'accès aux zones sécurisées est-il limité uniquement au personnel autorisé et essentiel ?","objectif":"La limitation de l'accès aux zones sécurisées est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21307,"chapitre":"Nettoyer le bureau et l'écran"}},
        {"model":"Questions","data":{"id_chapitre": 21307,"question":"Disposez-vous d'une politique de bureau et d'écran propre pour protéger les informations sensibles ?","objectif":"La mise en place de cette politique est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21307,"question":"Les employés sont-ils sensibilisés à la nécessité de verrouiller leurs écrans lorsqu'ils quittent leur poste de travail ?","objectif":"La sensibilisation au verrouillage des écrans est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21308,"chapitre":"Emplacement et protection des équipements"}},
        {"model":"Questions","data":{"id_chapitre": 21308,"question":"Les équipements critiques sont-ils placés dans des emplacements sécurisés ?","objectif":"La sécurisation de l'emplacement des équipements est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21308,"question":"Les équipements sensibles sont-ils protégés contre le vol ou le sabotage ?","objectif":"La protection des équipements contre le vol est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21309,"chapitre":"Sécurité des biens hors locaux"}},
        {"model":"Questions","data":{"id_chapitre": 21309,"question":"Les biens de l'entreprise utilisés hors des locaux sont-ils protégés par des mesures de sécurité appropriées ?","objectif":"La protection des biens hors locaux est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21309,"question":"Disposez-vous d'une politique spécifique pour la gestion des équipements mobiles en dehors des locaux ?","objectif":"La mise en place de cette politique est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21310,"chapitre":"Supports de stockage"}},
        {"model":"Questions","data":{"id_chapitre": 21310,"question":"Les supports de stockage sont-ils protégés contre les accès non autorisés ?","objectif":"La sécurisation des supports de stockage est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21310,"question":"Disposez-vous de procédures pour l'élimination sécurisée des supports de stockage obsolètes ?","objectif":"L'élimination sécurisée des supports est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21311,"chapitre":"Utilitaires de soutien"}},
        {"model":"Questions","data":{"id_chapitre": 21311,"question":"Les systèmes critiques disposent-ils d'utilitaires de soutien tels que des systèmes d'alimentation de secours ?","objectif":"La vérification des utilitaires de soutien est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21311,"question":"Les utilitaires de soutien sont-ils régulièrement testés pour garantir leur bon fonctionnement en cas de besoin ?","objectif":"Les tests réguliers des utilitaires sont jugés ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21312,"chapitre":"Sécurité du câblage"}},
        {"model":"Questions","data":{"id_chapitre": 21312,"question":"Disposez-vous de mesures pour sécuriser les câblages critiques contre les sabotages ou dommages accidentels ?","objectif":"La sécurisation des câblages est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21312,"question":"Les câblages sensibles sont-ils régulièrement inspectés et maintenus pour assurer leur intégrité ?","objectif":"L'inspection régulière des câblages est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21313,"chapitre":"Entretien de l'équipement"}},
        {"model":"Questions","data":{"id_chapitre": 21313,"question":"Disposez-vous de procédures d'entretien régulier pour vos équipements sensibles ?","objectif":"L'entretien régulier des équipements est jugé ..."}},
        {"model":"Questions","data":{"id_chapitre": 21313,"question":"Les pièces détachées ou de remplacement utilisées lors de l'entretien sont-elles sécurisées et conformes aux spécifications d'origine ?","objectif":"La vérification de la conformité des pièces détachées est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":213,"id_chapitre": 21314,"chapitre":"Élimination ou réutilisation sécurisée de l'équipement"}},
        {"model":"Questions","data":{"id_chapitre": 21314,"question":"Disposez-vous de procédures pour l'élimination sécurisée des équipements obsolètes ?","objectif":"La mise en place de procédures d'élimination est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21314,"question":"Les données stockées sur les équipements obsolètes sont-elles systématiquement effacées avant leur réutilisation ou élimination ?","objectif":"L'effacement des données est jugé ..."}},

        {"model":"Domaines","data":{"id_theme":21,"id_domaine":214,"domaine":"Audit d'architecture"}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21401,"chapitre":"Dispositifs d'extrémité des utilisateurs"}},
        {"model":"Questions","data":{"id_chapitre": 21401,"question":"Les dispositifs d'extrémité des utilisateurs sont-ils protégés par des solutions antivirus et pare-feu ?","objectif":"La protection des dispositifs d'extrémité est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21401,"question":"Des contrôles d'accès sont-ils en place pour empêcher l'utilisation non autorisée des dispositifs d'extrémité des utilisateurs ?","objectif":"La gestion des accès aux dispositifs est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21402,"chapitre":"Droits d'accès privilégiés"}},
        {"model":"Questions","data":{"id_chapitre": 21402,"question":"Les droits d'accès privilégiés sont-ils régulièrement révisés pour s'assurer qu'ils sont toujours justifiés ?","objectif":"La révision des accès privilégiés est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21402,"question":"Disposez-vous d'un processus de gestion des comptes privilégiés pour garantir une traçabilité des actions ?","objectif":"La gestion des comptes privilégiés est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21403,"chapitre":"Restriction de l'accès aux informations"}},
        {"model":"Questions","data":{"id_chapitre": 21403,"question":"Les accès aux informations sensibles sont-ils limités aux utilisateurs ayant besoin d'en connaître ?","objectif":"La restriction des accès est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21403,"question":"Disposez-vous de mécanismes pour révoquer rapidement l'accès aux informations en cas de changement de rôle ?","objectif":"La révision des droits d'accès en cas de changement est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21404,"chapitre":"Accès au code source"}},
        {"model":"Questions","data":{"id_chapitre": 21404,"question":"L'accès au code source est-il limité aux développeurs et aux responsables autorisés ?","objectif":"La limitation de l'accès au code source est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21404,"question":"Les modifications apportées au code source sont-elles suivies et auditées régulièrement ?","objectif":"L'audit des modifications de code source est jugé ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21405,"chapitre":"Authentification sécurisée"}},
        {"model":"Questions","data":{"id_chapitre": 21405,"question":"Les mécanismes d'authentification utilisés sont-ils basés sur plusieurs facteurs (MFA) ?","objectif":"L'authentification multi-facteurs est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21405,"question":"Les utilisateurs sont-ils sensibilisés à l'importance de ne pas partager leurs informations d'authentification ?","objectif":"La sensibilisation sur la gestion des informations d'authentification est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21406,"chapitre":"Gestion de la capacité"}},
        {"model":"Questions","data":{"id_chapitre": 21406,"question":"Disposez-vous d'outils pour surveiller la capacité des systèmes et éviter les surcharges ?","objectif":"La gestion proactive de la capacité des systèmes est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21406,"question":"Des prévisions de croissance sont-elles réalisées pour adapter les capacités de vos infrastructures IT ?","objectif":"La prévision des besoins en ressources est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21407,"chapitre":"Protection contre les logiciels malveillants"}},
        {"model":"Questions","data":{"id_chapitre": 21407,"question":"Disposez-vous d'outils de détection et de protection contre les logiciels malveillants sur tous les systèmes ?","objectif":"La protection contre les logiciels malveillants est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21407,"question":"Les systèmes sont-ils régulièrement mis à jour pour éviter les vulnérabilités liées aux logiciels malveillants ?","objectif":"La mise à jour des systèmes est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21408,"chapitre":"Gestion des vulnérabilités techniques"}},
        {"model":"Questions","data":{"id_chapitre": 21408,"question":"Disposez-vous d'un processus de gestion des vulnérabilités techniques avec une priorisation des correctifs ?","objectif":"La gestion proactive des vulnérabilités est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21408,"question":"Effectuez-vous des tests de pénétration pour identifier les vulnérabilités non détectées par vos systèmes ?","objectif":"Les tests de pénétration sont jugés ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21409,"chapitre":"Gestion de la configuration"}},
        {"model":"Questions","data":{"id_chapitre": 21409,"question":"Disposez-vous de politiques de gestion des configurations pour tous vos équipements IT ?","objectif":"La gestion des configurations est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21409,"question":"Les configurations des systèmes sont-elles régulièrement auditées et mises à jour selon les meilleures pratiques de sécurité ?","objectif":"L'audit des configurations est jugé ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21410,"chapitre":"Suppression d'informations"}},
        {"model":"Questions","data":{"id_chapitre": 21410,"question":"Disposez-vous de procédures pour la suppression sécurisée des informations sensibles sur vos systèmes ?","objectif":"La suppression sécurisée des informations est jugée ..."}},
        {"model":"Questions","data":{"id_chapitre": 21410,"question":"Utilisez-vous des outils de suppression définitive pour garantir que les informations ne peuvent pas être récupérées ?","objectif":"L'utilisation d'outils de suppression définitive est jugée ..."}},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21411,"chapitre":"Masquage des données" }},
        {"model":"Questions","data":{"id_chapitre": 21411,"question":"Utilisez-vous des techniques de masquage des données pour protéger les informations sensibles dans vos environnements de test ou de développement ?","objectif":"Le masquage des données est jugé ..." }},
        {"model":"Questions","data":{"id_chapitre": 21411,"question":"Disposez-vous de politiques de masquage de données pour limiter l'exposition des données à caractère personnel ?","objectif":"Le masquage des données à caractère personnel est jugé ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21412,"chapitre":"Prévention des fuites de données" }},
        {"model":"Questions","data":{"id_chapitre": 21412,"question":"Disposez-vous d'outils et de politiques de prévention des fuites de données (DLP) pour surveiller et contrôler les flux d'informations sensibles ?","objectif":"La mise en place de solutions DLP est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21412,"question":"Effectuez-vous des audits réguliers pour vérifier l'efficacité des politiques de prévention des fuites de données ?","objectif":"Les audits de prévention des fuites de données sont jugés ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21413,"chapitre":"Sauvegarde de l'information" }},
        {"model":"Questions","data":{"id_chapitre": 21413,"question":"Disposez-vous de processus réguliers pour sauvegarder les données critiques de votre organisation ?","objectif":"La sauvegarde des données est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21413,"question":"Les sauvegardes sont-elles chiffrées et stockées dans un emplacement sécurisé pour éviter tout accès non autorisé ?","objectif":"Le chiffrement des sauvegardes est jugé ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21414,"chapitre":"Redondance des installations de traitement de l'information" }},
        {"model":"Questions","data":{"id_chapitre": 21414,"question":"Disposez-vous de systèmes redondants pour garantir la disponibilité continue des services critiques en cas de panne matérielle ou de sinistre ?","objectif":"La redondance des systèmes est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21414,"question":"Les systèmes redondants sont-ils testés régulièrement pour vérifier leur bon fonctionnement en cas de basculement ?","objectif":"Les tests de basculement sont jugés ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21415,"chapitre":"Journalisation" }},
        {"model":"Questions","data":{"id_chapitre": 21415,"question":"Disposez-vous de solutions de journalisation pour enregistrer les événements de sécurité sur vos systèmes ?","objectif":"La journalisation des événements de sécurité est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21415,"question":"Les journaux d'audit sont-ils protégés contre les modifications non autorisées et stockés de manière sécurisée ?","objectif":"La protection des journaux est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21416,"chapitre":"Activités de suivi" }},
        {"model":"Questions","data":{"id_chapitre": 21416,"question":"Disposez-vous de systèmes de surveillance en temps réel pour détecter les activités suspectes ou anormales sur vos réseaux et systèmes ?","objectif":"La surveillance en temps réel est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21416,"question":"Les alertes générées par les systèmes de suivi sont-elles traitées et escaladées selon des procédures documentées ?","objectif":"La gestion appropriée des alertes de sécurité est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21417,"chapitre":"Synchronisation de l'horloge" }},
        {"model":"Questions","data":{"id_chapitre": 21417,"question":"Les horloges des systèmes critiques sont-elles synchronisées avec une source de temps fiable (comme NTP) ?","objectif":"La synchronisation des horloges est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21417,"question":"Les écarts de temps entre les systèmes sont-ils régulièrement surveillés pour éviter toute dérive significative ?","objectif":"La surveillance des écarts de temps est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21418,"chapitre":"Utilisation de programmes utilitaires privilégiés" }},
        {"model":"Questions","data":{"id_chapitre": 21418,"question":"Les accès aux programmes utilitaires privilégiés sont-ils strictement contrôlés et limités aux administrateurs autorisés ?","objectif":"Le contrôle des utilitaires privilégiés est jugé ..." }},
        {"model":"Questions","data":{"id_chapitre": 21418,"question":"Les actions effectuées avec des utilitaires privilégiés sont-elles enregistrées et auditées pour détecter tout usage anormal ?","objectif":"L'audit des actions menées avec des programmes utilitaires est jugé ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21419,"chapitre":"Installation de logiciels sur des systèmes opérationnels" }},
        {"model":"Questions","data":{"id_chapitre": 21419,"question":"L'installation de nouveaux logiciels sur les systèmes opérationnels est-elle soumise à des processus de validation et d'approbation ?","objectif":"La validation des logiciels avant installation est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21419,"question":"Les logiciels installés sont-ils régulièrement audités pour détecter la présence de versions non autorisées ou obsolètes ?","objectif":"L'audit régulier des logiciels installés est jugé ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21420,"chapitre":"Sécurité des réseaux" }},
        {"model":"Questions","data":{"id_chapitre": 21420,"question":"Les réseaux internes sont-ils segmentés pour limiter l'accès entre les différents départements ou zones de sécurité ?","objectif":"La segmentation des réseaux est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21420,"question":"Disposez-vous de mécanismes pour surveiller et filtrer les accès entrants et sortants sur vos réseaux ?","objectif":"Le filtrage et la surveillance des accès réseau sont jugés ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21421,"chapitre":"Sécurité des services de réseau" }},
        {"model":"Questions","data":{"id_chapitre": 21421,"question":"Les services réseau fournis par des tiers sont-ils soumis à des évaluations de sécurité régulières ?","objectif":"L'évaluation de la sécurité des services fournis par des tiers est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21421,"question":"Disposez-vous de contrats formalisant les exigences de sécurité pour les fournisseurs de services de réseau ?","objectif":"La formalisation des exigences de sécurité avec les fournisseurs est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21422,"chapitre":"Séparation des réseaux" }},
        {"model":"Questions","data":{"id_chapitre": 21422,"question":"Avez-vous mis en place une séparation stricte entre les réseaux publics et privés de votre organisation ?","objectif":"La séparation des réseaux est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21422,"question":"Disposez-vous de contrôles pour segmenter les différents réseaux internes en fonction des niveaux de sécurité ?","objectif":"La segmentation des réseaux internes est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21423,"chapitre":"Filtrage Web" }},
        {"model":"Questions","data":{"id_chapitre": 21423,"question":"Utilisez-vous des outils de filtrage Web pour contrôler et restreindre l'accès aux sites non sécurisés ou inappropriés ?","objectif":"Le filtrage Web est jugé ..." }},
        {"model":"Questions","data":{"id_chapitre": 21423,"question":"Les politiques de filtrage Web sont-elles révisées régulièrement pour s'adapter aux nouvelles menaces ?","objectif":"La révision régulière des politiques de filtrage Web est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21424,"chapitre":"Utilisation de la cryptographie" }},
        {"model":"Questions","data":{"id_chapitre": 21424,"question":"Les informations sensibles sont-elles chiffrées lors de leur stockage et de leur transmission ?","objectif":"L'utilisation du chiffrement est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21424,"question":"Disposez-vous de politiques de gestion des clés cryptographiques pour assurer leur sécurité ?","objectif":"La gestion sécurisée des clés est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21425,"chapitre":"Cycle de vie du développement sécurisé" }},
        {"model":"Questions","data":{"id_chapitre": 21425,"question":"Avez-vous intégré des pratiques de sécurité tout au long du cycle de vie de développement de vos logiciels ?","objectif":"L'intégration de la sécurité dans le cycle de vie du développement est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21425,"question":"Effectuez-vous des tests de sécurité à chaque phase du développement de vos applications ?","objectif":"Les tests de sécurité réguliers durant le développement sont jugés ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21426,"chapitre":"Exigences de sécurité des applications" }},
        {"model":"Questions","data":{"id_chapitre": 21426,"question":"Disposez-vous de directives pour définir les exigences de sécurité spécifiques à chaque application que vous développez ?","objectif":"La définition des exigences de sécurité pour chaque application est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21426,"question":"Les exigences de sécurité des applications sont-elles régulièrement mises à jour pour s'adapter aux nouvelles menaces ?","objectif":"La mise à jour des exigences de sécurité est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21427,"chapitre":"Principes d'architecture et d'ingénierie des systèmes sécurisés" }},
        {"model":"Questions","data":{"id_chapitre": 21427,"question":"Les principes de sécurité sont-ils intégrés dans la conception et l'architecture des systèmes de votre organisation ?","objectif":"L'intégration des principes de sécurité dans la conception des systèmes est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21427,"question":"Effectuez-vous des revues d'architecture pour évaluer la sécurité de vos systèmes avant leur déploiement ?","objectif":"La revue d'architecture est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21428,"chapitre":"Codage sécurisé" }},
        {"model":"Questions","data":{"id_chapitre": 21428,"question":"Utilisez-vous des pratiques de codage sécurisé pour minimiser les vulnérabilités dans vos applications ?","objectif":"L'adoption de pratiques de codage sécurisé est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21428,"question":"Vos développeurs sont-ils formés régulièrement sur les techniques de codage sécurisé ?","objectif":"La formation des développeurs sur le codage sécurisé est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21429,"chapitre":"Tests de sécurité en développement et en acceptation" }},
        {"model":"Questions","data":{"id_chapitre": 21429,"question":"Réalisez-vous des tests de sécurité pendant les phases de développement pour identifier les vulnérabilités ?","objectif":"Les tests de sécurité en développement sont jugés ..." }},
        {"model":"Questions","data":{"id_chapitre": 21429,"question":"Effectuez-vous des tests de pénétration ou d'audit de sécurité avant l'acceptation finale des projets ?","objectif":"Les tests de pénétration et audits de sécurité sont jugés ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21430,"chapitre":"Développement externalisé" }},
        {"model":"Questions","data":{"id_chapitre": 21430,"question":"Les projets de développement externalisés incluent-ils des clauses contractuelles relatives à la sécurité de l'information ?","objectif":"L'intégration de clauses de sécurité dans les contrats est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21430,"question":"Surveillez-vous régulièrement la conformité des prestataires en matière de sécurité de l'information pour les développements externalisés ?","objectif":"Le suivi de la conformité des prestataires est jugé ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21431,"chapitre":"Séparation des environnements de développement,de test et de production" }},
        {"model":"Questions","data":{"id_chapitre": 21431,"question":"Les environnements de développement,de test et de production sont-ils séparés pour éviter tout risque de contamination ?","objectif":"La séparation des environnements est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21431,"question":"Disposez-vous de contrôles stricts pour restreindre les accès aux différents environnements (développement,test,production) ?","objectif":"Le contrôle des accès aux environnements est jugé ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21432,"chapitre":"Gestion des changements" }},
        {"model":"Questions","data":{"id_chapitre": 21432,"question":"Disposez-vous d'un processus formel de gestion des changements pour examiner et approuver les modifications apportées aux systèmes critiques ?","objectif":"La gestion formelle des changements est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21432,"question":"Les impacts de sécurité sont-ils systématiquement évalués avant la mise en œuvre de tout changement sur les systèmes critiques ?","objectif":"L'évaluation des impacts de sécurité lors des changements est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21433,"chapitre":"Informations sur les tests" }},
        {"model":"Questions","data":{"id_chapitre": 21433,"question":"Les informations utilisées pour les tests sont-elles protégées de la même manière que les informations en production ?","objectif":"La protection des données utilisées pour les tests est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21433,"question":"Disposez-vous de politiques limitant l'utilisation de données réelles dans les environnements de test ?","objectif":"La restriction de l'utilisation de données réelles pour les tests est jugée ..." }},
        {"model":"Chapitres","data":{"id_domaine":214,"id_chapitre": 21434,"chapitre":"Protection des systèmes d'information pendant les tests d'audit" }},
        {"model":"Questions","data":{"id_chapitre": 21434,"question":"Des mesures sont-elles en place pour protéger les systèmes d'information pendant la réalisation des audits ou des tests de sécurité ?","objectif":"La protection des systèmes pendant les audits est jugée ..." }},
        {"model":"Questions","data":{"id_chapitre": 21434,"question":"Les résultats des tests d'audit sont-ils traités de manière confidentielle et sécurisée ?","objectif":"Le traitement sécurisé et confidentiel des résultats d'audit est jugé ..." }}
    ]
